---
- name: Setup Americas Best Racing Servers
  hosts: all
  become: yes
  become_user: root

  roles:
    - web

- name: Setup CMS Servers
  hosts: tag_Name_CfnInitStack_CMS
  become: yes
  become_user: root

  roles:
    - cms