---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Import Remi GPG key.
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present

    - name: Install  Remi repo.
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present

    - name: Install php packages
      yum:
        name: "{{ php_packages }}"
        state: present
        disable_plugin: priorities
        disablerepo: remi-safe
        enablerepo: remi-php72
      vars:
        php_packages:
          - php-fpm
          - php-cli
          - php-xml
          - php-xmlrpc
          - php-mysql
          - php-gd
          - php-pdo
      notify:
        restart php-fpm

    - name: Copy php ini configuration for drupal
      template:
        src: root/etc/php.ini
        dest: /etc/php.ini
        owner: root
        group: root
        mode: 0644
      notify:
        restart php-fpm

    - name: Copy php-fpm configuration for drupal
      template:
        src: root/etc/php-fpm.d/www.conf
        dest: /etc/php-fpm.d/www.conf
        owner: root
        group: root
        mode: 0644
      notify:
        restart php-fpm

    - name: php-fpm service state
      service:
        name: php-fpm
        state: started
        enabled: yes

  handlers:
    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted