---
- name: Setup Americas Best Racing Servers
  hosts: all
  become: yes
  become_user: root

  roles:
    - web

- name: Setup CMS Servers
  hosts: tag_Name_prod_abr_cms:tag_Name_stage_abr_cms
  become: yes
  become_user: root

  roles:
    - cms