---
- name: reload bashrc
  shell: >
    source /etc/profile

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted