---
- name: Install certbot and plugins
  yum:
    name: "{{ certbot_packages }}"
    state: present
  vars:
    certbot_packages:
      - certbot
      - python-certbot-nginx
      - python2-certbot-dns-route53.noarch

- name: Create deploy user
  ansible.builtin.user:
    name: deploy
    groups: nginx

- name: Set up authorized keys
  ansible.posiix.authorized_key:
    user: deploy
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/a