---
- name: Install certbot and plugins
  yum:
    name:
      - certbot
      - python-certbot-nginx
      - python2-certbot-dns-route53.noarch
    state: present
  register: cbot_installed

- name: Get and install certificate
  shell: >
    echo certbot -a dns-route53 -i nginx --register-unsafely-without-email --agree-tos -d {{ server_name }} > /tmp/cb.out
  when: cbot_installed.changed

- name: Install drush
  yum:
    name: drush
    state: present
    disable_plugin: priorities
    enablerepo: remi-php72    

- name: Enable certbot-renew timer
  ansible.builtin.systemd:
    name: certbot-renew.timer
    enabled: true
    state: started

- name: Create deploy user
  ansible.builtin.user:
    name: deploy
    groups: nginx

- name: Set up deploy authorized keys
  authorized_key:
    user: deploy
    state: present
    key: '{{ item }}'
  with_file:
    - public-keys/deploy/a

- name: Create dba user
  ansible.builtin.user:
    name: mysqldba
    
- name: Set up dba authorized keys
  authorized_key:
    user: mysqldba
    state: present
    key: '{{ item }}'
  with_file:
    - public-keys/mysqldba/b

- name: Set up cron logging
  copy:
    src: 22-drupal_cron.conf
    dest: /etc/rsyslog.d/22-drupal_cron.conf
    owner: root
    group: root
    mode: 0644
  notify: restart syslog
  
- name: Set up cron jobs
  copy:
    src: nginx
    dest: /var/spool/cron/nginx
    owner: nginx
    group: nginx
    mode: 0600
  notify: restart cron