---
- name: Install Cloudwatch Agent
  yum:
    name: amazon-cloudwatch-agent
    state: latest

- name: Copy amazon-cloudwatch-agent.json
  template:
    src: amazon-cloudwatch-agent.json.j2
    dest: "{{ config_location }}"
  register: agent_config

- name: Start the CloudWatch agent using the command line
  shell: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:{{ config_location }}
  when: agent_config.changed